version: '3'

services:
  # 后端服务
  backend:
    build:
      context: ./box_back/box_back
      dockerfile: Dockerfile
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,172.31.3.252
    networks:
      - app-network
    restart: unless-stopped

  # 前端服务
  frontend:
    build:
      context: ./box_show
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - backend

  # Nginx服务 - 作为反向代理和静态文件服务器
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./box_show/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge