version: '3'

services:
  # 后端服务
  backend:
    image: box_p-backend
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,aimls.uk,www.aimls.uk
    networks:
      - app-network
    restart: unless-stopped

  # 前端服务
  # frontend:
  #   image: box_p-frontend
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 5G
  #   networks:
  #     - app-network
  #   depends_on:
  #     - backend

  # Nginx服务
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/private:/etc/ssl/private:ro
      - ./box_show/build:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro  # 添加这一行
    depends_on:
      # - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge